In [1]:
import numpy as np
l=[1,2,3,4,5,6,7,8]
a=np.array(l)     # create array with numpy
print(a)
print(a+1)       # add by 1 in all element 
print(a*2)       # mul by 2 in all element 

[1 2 3 4 5 6 7 8]
[2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16]


In [22]:
# addition of two list
l1=np.array([1,2,3,4,5])
l2=np.array([6,7,8,9,10])
s=l1+l2
print(s)
m=l1*l2
print(m)

[ 7  9 11 13 15]
[ 6 14 24 36 50]


In [3]:
# linspace() -----divided equal part

lspace=np.linspace(1,5,10)
lspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [4]:
x=[[1,2,3],[4,5,6],[7,8,9]]
ar=np.array(x)
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
ar.sum(axis=1)


array([ 6, 15, 24])

In [6]:
ar.sum(axis=0)

array([12, 15, 18])

In [9]:
# transpose of matrix
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [8]:
ar.size

9

In [10]:
one=np.array([1,77,55,99,33])
one.argsort()

array([0, 4, 2, 1, 3], dtype=int64)

In [14]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)